
class ConfigJogo:
    LARGURA_TELA = 600
    ALTURA_TELA = 400
    COR_BARRA = (0, 0, 0)
    COR_BOLA = (0, 0, 0)
    COR_ESTADO = (0, 0, 255)
    COR_TITULO = (0, 0, 0)
    VELOCIDADE_BOLA = 0.15
    VELOCIDADE_BARRAS = 0.2
    ALTURA_PLACAR = 0.1 * ALTURA_TELA
    ALTURA_TEMPO = 0.15 * ALTURA_TELA
    FONTE_TITULO = 72
    FONTE_SUBTITULO = 36
