class ConfigJogo:
    COR_TITULO = (0, 0, 0)
    FONTE_SUBTITULO = 36
    FONTE_TITULO = 72
    LARGURA_TELA = 1280
    ALTURA_TELA = 640
    VELOCIDADE_PERSONAGEM = 0.2
    VELOCIDADE_MINIONS = 0.1
    POS_INICIAL_PERSONAGENS = (LARGURA_TELA // 2, ALTURA_TELA // 2)
    TAMANHO_FONTE = 48
    ALTURA_PERSONAGEM = (0.1 * ALTURA_TELA)
    LARGURA_PERSONAGEM = (0.02 * LARGURA_TELA)
    COR_PERSONAGEM = (0, 0, 0)
